[default]
description = "Default permissions for the plugin"
permissions = ["allow-ping", "allow-generate-secure-key", "allow-list-keys", "allow-sign-with-key", "allow-delete-key", "allow-check-secure-element-support"]
